// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Passenger.Core.Database;

namespace EngineeringWork.Web.Migrations
{
    [DbContext(typeof(PassengerContext))]
    [Migration("20190919114146_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EngineeringWork.Core.Domain.DailyRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<Guid>("DriverId");

                    b.Property<Guid?>("RouteId");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RouteId");

                    b.ToTable("DailyRoutes");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<Guid>("UserId");

                    b.Property<Guid?>("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Node");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AddressId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Passenger");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.PassengerNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("DailyRouteId");

                    b.Property<Guid?>("NodeId");

                    b.Property<Guid?>("PassengerId");

                    b.HasKey("Id");

                    b.HasIndex("DailyRouteId");

                    b.HasIndex("NodeId");

                    b.HasIndex("PassengerId");

                    b.ToTable("PassengerNode");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Revoke");

                    b.Property<string>("Token");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EndNodeId");

                    b.Property<Guid?>("StartNodeId");

                    b.HasKey("Id");

                    b.HasIndex("EndNodeId");

                    b.HasIndex("StartNodeId");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<string>("Salt");

                    b.Property<DateTime>("UpdatedAt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("Name");

                    b.Property<int>("Seats");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.DailyRoute", b =>
                {
                    b.HasOne("EngineeringWork.Core.Domain.Driver")
                        .WithMany("DailyRoutes")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EngineeringWork.Core.Domain.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.Driver", b =>
                {
                    b.HasOne("EngineeringWork.Core.Domain.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EngineeringWork.Core.Domain.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.Passenger", b =>
                {
                    b.HasOne("EngineeringWork.Core.Domain.Node", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.PassengerNode", b =>
                {
                    b.HasOne("EngineeringWork.Core.Domain.DailyRoute")
                        .WithMany("PassengerNodes")
                        .HasForeignKey("DailyRouteId");

                    b.HasOne("EngineeringWork.Core.Domain.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId");

                    b.HasOne("EngineeringWork.Core.Domain.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId");
                });

            modelBuilder.Entity("EngineeringWork.Core.Domain.Route", b =>
                {
                    b.HasOne("EngineeringWork.Core.Domain.Node", "EndNode")
                        .WithMany()
                        .HasForeignKey("EndNodeId");

                    b.HasOne("EngineeringWork.Core.Domain.Node", "StartNode")
                        .WithMany()
                        .HasForeignKey("StartNodeId");
                });
#pragma warning restore 612, 618
        }
    }
}
