language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 2.0 
branches:
 - only:
   - master
   - develop
 
before_script:
 - dotnet restore
 
script:
 - dotnet build .\src\EngineeringWork\EngineeringWork.sln
 - dotnet test .\test\EngineringWork.UnitTest\EngineringWork.UnitTest.csproj