language: csharp
sudo: required
dist: xenial 
mono: none
dotnet: 2.2 
branches:
 - only:
   - master
   - develop
 
script:
 - dotnet build .\src\EngineeringWork\EngineeringWork.sln
 - dotnet test .\test\EngineringWork.UnitTest\EngineringWork.UnitTest.csproj